on: push
#  schedule:
#  - cron: '0 0 * * *'
name: Update indices every day
jobs:
  updateAlgoliaIndexKongEE:
    name: Index Kong EE Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lookup
      run: |
        ls -la ${{ github.workspace }}/algolia
        cat ${{ github.workspace }}/algolia/config-ee.json
    - name: Run docsearch for Kong EE Docs
      uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_api_key: ${{ secrets.API_KEY }}
        algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        file: ${{ github.workspace }}/algolia/config-ee.json
  updateAlgoliaIndexKongStudio:
    name: Index Kong Studio Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run docsearch for Kong Studio Docs
      uses: darrenjennings/algolia-docsearch-action@master
      with:
        algolia_api_key: ${{ secrets.API_KEY }}
        algolia_application_id: ${{ secrets.ALGOLIA_APPLICATION_ID }}
        file: ${{ github.workspace }}/algolia/config-studio.json
